src/main/java/com/assu/server/domain/partnership/controller/PartnershipController.java
src/main/java/com/assu/server/domain/partnership/service/PartnershipServiceImpl.java
src/main/java/com/assu/server/domain/user/controller/StudentController.java
src/main/java/com/assu/server/global/apiPayload/code/status/SuccessStatus.java
src/main/java/com/assu/server/global/config/SecurityConfig.java

제휴내역 조회 수정

---

src/main/java/com/assu/server/domain/user/entity/Student.java

> #
> student 엔티티에서 studentNumber 컬럼 삭제

[Refactor/#45] student 엔티티 수정

---

src/main/java/com/assu/server/domain/admin/controller/AdminController.java
src/main/java/com/assu/server/domain/certification/controller/CertificationController.java
src/main/java/com/assu/server/domain/deviceToken/controller/DeviceTokenController.java
src/main/java/com/assu/server/domain/inquiry/controller/InquiryController.java
src/main/java/com/assu/server/domain/mapping/controller/StudentAdminController.java
src/main/java/com/assu/server/domain/notification/controller/NotificationController.java
src/main/java/com/assu/server/domain/partner/controller/PartnerController.java
src/main/java/com/assu/server/domain/partnership/controller/PaperController.java
src/main/java/com/assu/server/domain/partnership/converter/PartnershipConverter.java
src/main/java/com/assu/server/domain/review/controller/ReviewController.java
src/main/java/com/assu/server/domain/store/controller/StoreController.java
src/main/java/com/assu/server/domain/suggestion/controller/SuggestionController.java
src/main/java/com/assu/server/domain/suggestion/converter/SuggestionConverter.java
src/main/java/com/assu/server/domain/suggestion/dto/SuggestionResponseDTO.java
src/main/java/com/assu/server/domain/suggestion/service/SuggestionServiceImpl.java
src/main/java/com/assu/server/domain/user/controller/StudentController.java
src/main/java/com/assu/server/global/config/SecurityConfig.java

> #48 
> pd, security config 수정

[Mod/#48] pd, security config 수정

---

.github/workflows/cd.yml

[DEPLOY/#56] secrets 복사 경로 수정

---

deploy.sh

[DEPLOY/#59] blue green 전환을 위해 deploy.sh 수정

---

deploy.sh
src/main/java/com/assu/server/global/config/RedisConfig.java

[DEPLOY/#62] deploy.sh 수정 및 redis properties관련 문제 수정

---

src/main/java/com/assu/server/domain/notification/service/NotificationCommandService.java
src/main/java/com/assu/server/domain/notification/service/NotificationCommandServiceImpl.java
src/test/java/com/assu/server/ServerApplicationTests.java
src/test/resources/application-test.yml

- 알림 전송 메소드 분리
> #71 
> 알림 전송 메소드 분리함
https://clumsy-seeder-416.notion.site/2491197c19ed802fa84cce9e9300fbdb?source=copy_link

[FEAT/#71] 알림 전송 메소드 분리

---

docker-compose.yml

[HOTFIX] docker network external 처리

---

src/main/java/com/assu/server/domain/admin/repository/AdminRepository.java
src/main/java/com/assu/server/domain/auth/controller/AuthController.java
src/main/java/com/assu/server/domain/certification/controller/CertificationController.java
src/main/java/com/assu/server/domain/certification/converter/CertificationConverter.java
src/main/java/com/assu/server/domain/certification/dto/CertificationRequestDTO.java
src/main/java/com/assu/server/domain/certification/dto/CertificationResponseDTO.java
src/main/java/com/assu/server/domain/certification/service/CertificationServiceImpl.java
src/main/java/com/assu/server/domain/user/controller/StudentController.java

> #82
2. certification 로직 일부 수정
3. admin 회원가입시 department, university 받도록 수정
4. (3) 기반으로 matching admin 함수 로직 변경

[FIX/#82] admin 회원가입 수정 및 certification dto 수정

---

src/main/java/com/assu/server/domain/auth/security/jwt/JwtAuthFilter.java
src/main/java/com/assu/server/global/config/SecurityConfig.java

[FIX/#86] jwt white list edit

---

src/main/java/com/assu/server/domain/admin/entity/Admin.java
src/main/java/com/assu/server/domain/auth/controller/AuthController.java
src/main/java/com/assu/server/domain/auth/dto/common/UserBasicInfo.java
src/main/java/com/assu/server/domain/auth/dto/login/LoginResponse.java
src/main/java/com/assu/server/domain/auth/dto/signup/SignUpResponse.java
src/main/java/com/assu/server/domain/auth/dto/signup/student/StudentTokenAuthPayload.java
src/main/java/com/assu/server/domain/auth/schduler/MemberCleanupScheduler.java
src/main/java/com/assu/server/domain/auth/security/adapter/CommonAuthAdapter.java
src/main/java/com/assu/server/domain/auth/security/adapter/SSUAuthAdapter.java
src/main/java/com/assu/server/domain/auth/service/AuthService.java
src/main/java/com/assu/server/domain/auth/service/AuthServiceImpl.java
src/main/java/com/assu/server/domain/auth/service/LoginServiceImpl.java
src/main/java/com/assu/server/domain/auth/service/SignUpServiceImpl.java
src/main/java/com/assu/server/domain/auth/service/WithdrawalService.java
src/main/java/com/assu/server/domain/auth/service/WithdrawalServiceImpl.java
src/main/java/com/assu/server/domain/member/controller/MemberController.java
src/main/java/com/assu/server/domain/member/converter/MemberConverter.java
src/main/java/com/assu/server/domain/member/dto/MemberRequestDTO.java
src/main/java/com/assu/server/domain/member/dto/MemberResponseDTO.java
src/main/java/com/assu/server/domain/member/entity/Member.java
src/main/java/com/assu/server/domain/member/repository/MemberRepository.java
src/main/java/com/assu/server/domain/member/service/MemberService.java
src/main/java/com/assu/server/domain/member/service/MemberServiceImpl.java
src/main/java/com/assu/server/domain/user/entity/enums/Department.java
src/main/java/com/assu/server/domain/user/entity/enums/Major.java
src/main/java/com/assu/server/domain/user/entity/enums/University.java
src/main/java/com/assu/server/global/apiPayload/code/status/ErrorStatus.java

> close #89 
> close #92 
- 관리자 및 학생 회원가입 시 department 필드 반영
- ENUM 매핑
- 회원탈퇴 API 개발
- Soft delete후 30일 뒤 스케줄러로 완전 삭제 -> 삭제해야할 연관 내용 여기에 넣어주세요
- 회원가입 및 로그인 API에 기본 정보 응답에 포함 
-  노션 및 스웨거 버저닝 완료
MemberCleanupScheduler.cleanupDeletedMembers 에 삭제해야할 Cascade 아닌 연관 엔티티 삭제 내용 여기에 넣어주세요

[REFACTOR/#89] 로그인 및 회원가입 리팩토링 / [FEAT/#92] 회원탈퇴 API

---

src/main/java/com/assu/server/domain/chat/service/ChatServiceImpl.java

refactor/#38 - 채팅방 생성 api 수정

---

src/main/java/com/assu/server/global/config/SecurityConfig.java

[FIX/#82] map 만 풀어서 조정

---

src/main/java/com/assu/server/domain/auth/controller/AuthController.java
src/main/java/com/assu/server/global/apiPayload/code/status/SuccessStatus.java
src/main/java/com/assu/server/global/config/SecurityConfig.java

[FIX] logout delete 매핑 -> post 매핑

---

src/main/java/com/assu/server/domain/map/service/MapServiceImpl.java
src/main/java/com/assu/server/domain/partnership/repository/PaperContentRepository.java

[REFACTOR/#110] getStores 필터링 수정

---

src/main/java/com/assu/server/domain/map/service/MapServiceImpl.java
src/main/java/com/assu/server/domain/partnership/repository/PaperContentRepository.java

[BUG/#110] 쿼리 에러 수정

---

src/main/java/com/assu/server/domain/map/service/MapServiceImpl.java
src/main/java/com/assu/server/domain/partnership/repository/PaperContentRepository.java

[BUG/#110] 중복 쿼리 수정

---

src/main/java/com/assu/server/domain/inquiry/controller/InquiryController.java
src/main/java/com/assu/server/domain/inquiry/service/ProfileImageService.java
src/main/java/com/assu/server/domain/inquiry/service/ProfileImageServiceImpl.java
src/main/java/com/assu/server/infra/s3/AmazonS3Manager.java

[Feat/#128] profile image get

---

src/main/java/com/assu/server/domain/auth/controller/AuthController.java
src/main/java/com/assu/server/domain/auth/dto/verification/VerificationRequestDTO.java
src/main/java/com/assu/server/domain/auth/service/SSUAuthServiceImpl.java
src/main/java/com/assu/server/domain/auth/service/VerificationService.java
src/main/java/com/assu/server/domain/auth/service/VerificationServiceImpl.java
src/main/java/com/assu/server/domain/user/entity/enums/Department.java
src/main/java/com/assu/server/domain/user/entity/enums/Major.java

> closes #131 
- 전화번호 및 이메일 중복 API 추가
- Major Department 추가

[FEAT/#131] 전화번호 및 이메일 중복 API 추가 & Major Department 추가

---

src/main/java/com/assu/server/domain/auth/controller/AuthController.java
src/main/java/com/assu/server/domain/common/entity/enums/ReportedStatus.java
src/main/java/com/assu/server/domain/partnership/service/PaperQueryServiceImpl.java
src/main/java/com/assu/server/domain/report/controller/ReportController.java
src/main/java/com/assu/server/domain/report/dto/ReportRequestDTO.java
src/main/java/com/assu/server/domain/report/dto/ReportResponseDTO.java
src/main/java/com/assu/server/domain/report/entity/Report.java
src/main/java/com/assu/server/domain/report/entity/enums/ReportStatus.java
src/main/java/com/assu/server/domain/report/entity/enums/ReportTargetType.java
src/main/java/com/assu/server/domain/report/entity/enums/ReportType.java
src/main/java/com/assu/server/domain/report/event/ReportProcessedEvent.java
src/main/java/com/assu/server/domain/report/exception/ReportException.java
src/main/java/com/assu/server/domain/report/repository/ReportRepository.java
src/main/java/com/assu/server/domain/report/service/ReportService.java
src/main/java/com/assu/server/domain/report/service/ReportServiceImpl.java
src/main/java/com/assu/server/domain/report/service/ReportStatusSyncService.java
src/main/java/com/assu/server/domain/review/entity/Review.java
src/main/java/com/assu/server/domain/review/repository/ReviewRepository.java
src/main/java/com/assu/server/domain/review/service/ReviewServiceImpl.java
src/main/java/com/assu/server/domain/suggestion/entity/Suggestion.java
src/main/java/com/assu/server/domain/suggestion/repository/SuggestionRepository.java
src/main/java/com/assu/server/domain/suggestion/service/SuggestionServiceImpl.java
src/main/java/com/assu/server/domain/user/entity/Student.java
src/main/java/com/assu/server/global/apiPayload/code/status/ErrorStatus.java
src/main/java/com/assu/server/global/apiPayload/code/status/SuccessStatus.java

> closes #149 
학생/리뷰/건의글 신고 API 구축
신고 엔티티 생성 -> 이벤트 처리 -> 비동기로 각 신고당한 엔티티의 ReportedStatus 필드 변경 -> 조회 불가
Todo: 추후에 관리자가 신고 수락 혹은 거절 시 이벤트 처리 구현 필요

[FEAT/#149] 학생/리뷰/건의글 신고 API 구축

---

src/main/java/com/assu/server/domain/partnership/repository/PaperRepository.java
src/main/java/com/assu/server/domain/partnership/service/PartnershipServiceImpl.java
src/main/java/com/assu/server/domain/review/service/ReviewServiceImpl.java
src/main/java/com/assu/server/domain/store/entity/Store.java
src/main/java/com/assu/server/domain/store/repository/StoreRepository.java

> #157
- 대기 중인 제휴 제안서 삭제 API
- 리뷰 작성 API
> 대기 중인 제휴 제안서 삭제
> 가게 평점 반영

[Refactor/#157] modify apis

---

src/main/java/com/assu/server/domain/partnership/controller/PartnershipController.java
src/main/java/com/assu/server/domain/partnership/converter/PartnershipConverter.java
src/main/java/com/assu/server/domain/partnership/dto/PartnershipResponseDTO.java
src/main/java/com/assu/server/domain/partnership/service/PartnershipService.java
src/main/java/com/assu/server/domain/partnership/service/PartnershipServiceImpl.java

[Develop] v1.23

---

src/main/java/com/assu/server/domain/partnership/service/PartnershipServiceImpl.java

> api가 BLANK인 제안서도 감지할 수  있도록 수정

[Refactor/#169] 제안서 상태 확인 핫픽스

---

src/main/java/com/assu/server/domain/deviceToken/repository/DeviceTokenRepository.java
src/main/java/com/assu/server/domain/notification/repository/NotificationOutboxRepository.java
src/main/java/com/assu/server/domain/notification/service/NotificationListener.java
src/main/java/com/assu/server/domain/notification/service/OutboxStatusService.java
src/main/java/com/assu/server/infra/firebase/FcmClient.java
src/main/resources/application.yml

[DEPLOY] v.28 디바이스 토큰 에러 수정
